#!/bin/bash

DEST_PATH=..
BASE_URL="http://downloads.asterisk.org/pub/telephony/libpri"
TARBALL_PREFIX="libpri-"
SRC_DIR_PREFIX="libpri-"
PKG_NAME="libpri"
DFSG_EXCLUDE_PATTERNS=

UPVERSION=$(cat debian/tools/SOURCE-VERSION)
FILENAME="${PKG_NAME}.orig.tar.gz"

UPFILENAME="${PKG_NAME}_${UPVERSION}.orig.tar.gz"
URL="${BASE_URL}/${PKG_NAME}-${UPVERSION}.tar.gz"

VERSION=$(dpkg-parsechangelog| grep Version: | awk -F": " '{print $NF}' | sed -ne 's/^\(\([0-9]\+\):\)\?\(.*\)-.*/\3/p')
TAR_ORIG=$PKG_NAME"_"$VERSION.orig.tar.gz

if [ -e "${DEST_PATH}/${TAR_ORIG}" ]; then
	echo "A tarball already exist for this version ; remove it if you want to regenerate."
	exit 0
fi

echo "Downloading ${UPFILENAME} from ${URL}"
wget -nv -T10 -t3 -O ${DEST_PATH}/${TAR_ORIG} ${URL}
if [ $? != 0 ]; then
	rm -f ${DEST_PATH}/${TAR_ORIG}
	echo "Could not find tarball."
	exit 2
fi

echo "Done !"

